name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Release tag

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Sqlize
        run: python sqlize.py

      - name: Extract License
        run: cat LICENSE | awk '/CC BY-SA License/,0' > BFRPG_LICENSE

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'BFRPG_LICENSE,monsterdata.*'
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.tag }}
